# Generated by Django 6.1 on 2026-08-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auth_user_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
