# Generated by Django 6.0.5 on 2026-09-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_todoitem_options_bookmark_idea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='theme',
            field=models.CharField(choices=[('sulfur_caves', 'Сіркові печери'), ('amethyst', 'Аметистова'), ('trial_palace', 'Палац випробувань')], default='sulfur_caves', max_length=20),
        ),
    ]
