# Generated by Django 6.0.5 on 2026-09-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_world_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='source_type',
            field=models.CharField(choices=[('player', 'Player'), ('location', 'Location'), ('wiki_page', 'Wiki Page'), ('project', 'Project'), ('todo', 'Todo'), ('event', 'Event'), ('note', 'Note'), ('bookmark', 'Bookmark'), ('idea', 'Idea')], max_length=20),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='target_type',
            field=models.CharField(choices=[('player', 'Player'), ('location', 'Location'), ('wiki_page', 'Wiki Page'), ('project', 'Project'), ('todo', 'Todo'), ('event', 'Event'), ('note', 'Note'), ('bookmark', 'Bookmark'), ('idea', 'Idea')], max_length=20),
        ),
    ]
