# Generated by Django 6.0.5 on 2026-09-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_relationship_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='emoji',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='infobox',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='world_date',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='world_date_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
