# Generated by Django 6.0.5 on 2026-09-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_userprofile_and_notifications'),
        ('api', '0008_wikipage_emoji_wikipage_infobox_wikipage_tags_and_more'),
    ]

    operations = [
    ]
