# Generated by Django 6.0.5 on 2026-09-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_world_theme'),
        ('api', '0007_add_userprofile_and_notifications'),
    ]

    operations = [
    ]
