# Generated by Django 6.0.5 on 2026-09-02 06:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cleanup_duplicate_owner_memberships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.user_avatar_upload_path),
        ),
    ]
