# Generated by Django 6.1 on 2026-09-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_pale_garden_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
