# Generated by Django 6.1 on 2026-09-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
