# Generated by Django 6.1 on 2026-09-13 16:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_cleanup_rolled_back_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.user_cover_upload_path),
        ),
    ]
